# Generated by Django 5.1.2 on 2024-10-27 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('fisica', 'Fisica'), ('juridica', 'Juridica')], default='fisica', max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('pessoa_contato', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_informar', 'Não informar')], default='nao_informar', max_length=15)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_bacen', models.CharField(blank=True, max_length=20, null=True)),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('ie_rg', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True)),
                ('suframa', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='clientes_fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_familia', models.CharField(max_length=100)),
                ('sub_familia', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=100)),
                ('pessoa_contato', models.CharField(max_length=100)),
                ('fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_bacen', models.CharField(blank=True, max_length=20, null=True)),
                ('cnpj_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('ie_rg', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=100)),
                ('sub_grupo_nivel_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_grupo_nivel_2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.CharField(max_length=50, unique=True)),
                ('cod_barras', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao', models.CharField(max_length=200)),
                ('estoque', models.PositiveIntegerField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lucro_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tamanho', models.CharField(blank=True, max_length=50, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtos_fotos/')),
                ('familia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.familiaproduto')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedores')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grupoproduto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentarEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('descricao_movimentacao', models.TextField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produtos')),
            ],
        ),
    ]
