# Generated by Django 5.1.2 on 2024-10-15 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_alter_itempedido_pedido_alter_itempedido_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
    ]
